### ISSUE TITLE
dot character can not trigger class member list and how to disable fuzzy complete?

### ISSUE THREAD

**Issue by maobaoqi** [tigersoldier/company-lsp#112]
Hi, thanks for creating so great tool. 
I use it for C/C++ and have two questions:
1.In cpp file, there is a class object but can not pop complete menu when type dot character after obejct variable.
2. In some cases, fuzzy complete may list many no necessary items, can we disabled it?

**Comment by yyoncho** [comment]
1. `(setq company-minimum-prefix-length 0)` (probably)
2. I think that fuzzy matching is implemented on the server for ccls/clangd and I think that you cannot enforce string matching on the client at this point(there is no such option).

**Comment by maobaoqi** [comment]
@yyoncho  Setting `company-minimum-prefix-length` to 0 can not solve the question. thanks for your reply.
