### ISSUE TITLE
Yasnippets stopped working after installing ccls

### ISSUE THREAD

**Issue by muntasir1** [tigersoldier/company-lsp#116]
I installed ccls to get intelligent code completion, but after installing it my yasnippets no longer show up in the autocomplete suggestions. When autocomplete suggestions show up they have no snippets in them. I looked at the company-backends variable and it lists company-lsp as its first option. 

Any way to get my snippet suggestions back in the autocomplete popup? im using spacemacs on windows.

**Comment by tigersoldier** [comment]
Try making `company-backends` containing a list `(company-lsp company-yasnippet)` as the first element. For example, if your current value of `company-backends` is `(company-lsp company-capf)`, change that to be `((company-lsp company-yasnippet) company-capf)`.

Read the Grouped Backends section of the documentation of `company-backends`.
