### ISSUE TITLE
why get 1 in function?

### ISSUE THREAD

**Issue by glepnir** [tigersoldier/company-lsp#125]
@yyoncho  When i confirm the completion . i got 1 in function ..need help..
```
fmt.Println( 1 )  <----- 1 ?
```
![image](https://user-images.githubusercontent.com/41671631/66570673-ab22f380-eba0-11e9-8be1-33b75bc59f44.png)

**Comment by yyoncho** [comment]
see https://github.com/emacs-lsp/lsp-mode/issues/846

**Comment by glepnir** [comment]
ok ! got it
