### ISSUE TITLE
[Question] Where to implement fuzzy match.

### ISSUE THREAD

**Issue by jcs090218** [tigersoldier/company-lsp#131]
I have a code that could do the fuzzy match with `flx`. But whatever I have applied the completion menu order goes back to original. Is there a place so I could implement fuzzy match that would apply? Thanks!

**Comment by yyoncho** [comment]
@jcs090218 the fuzzy match is already implemented -         (setq company-lsp-cache-candidates 'auto) and check whether it is enabled for your language server in company-lsp-filter-candidates

**Comment by jcs090218** [comment]
@yyoncho Cool, I didn't realize this! Thanks! Close this issue now!
