### ISSUE TITLE
Cannot initialize company-lsp through company-begin-backend

### ISSUE THREAD

**Issue by TakaakiFuruse** [tigersoldier/company-lsp#143]
Because of [this commit](https://github.com/emacs-lsp/lsp-mode/commit/1caee9282638889bcdcacdad73d58490451859d1#diff-b1e9bc82c3b6bd6e95470e18ee41a19bL4715) on lsp-mode which changed some method names, [on latest commit](https://github.com/tigersoldier/company-lsp/commit/f921ffa0cdc542c21dc3dd85f2c93df4288e83bd), company-lsp fails to initialize.

The message is "Error processing message (void-function lsp--sort-completions)."

(When I have just removed [this line](https://github.com/tigersoldier/company-lsp/blob/master/company-lsp.el#L424) it started working.)

**Comment by yyoncho** [comment]
@TakaakiFuruse company-lsp is no longer supported - if you delete, lsp-mode will pick company-capf. 

(cc @ericdallo)

**Comment by TakaakiFuruse** [comment]
@yyoncho 
Thanks, I didn't know that. 
Let me close this issues.

**Comment by ericdallo** [comment]
https://github.com/emacs-lsp/lsp-mode/pull/1983
