### ISSUE TITLE
company-lsp not on MELPA?

### ISSUE THREAD

**Issue by licht1stein** [tigersoldier/company-lsp#147]
![image](https://user-images.githubusercontent.com/35418634/110320565-2cdab300-8019-11eb-9722-8352189260dd.png)

**Comment by jasonmiu** [comment]
I cannot find `company-lsp`  with the  `package-list-packages` too.

**Comment by NobbZ** [comment]
Please see melpa/melpa#7461, it seems as if it got removed.

**Comment by adrien-barret** [comment]
@NobbZ  did you found any workaround ?

**Comment by NobbZ** [comment]
For now I just removed it from my configuration to make it able to build again. Will look for alternatives during the comming weekend.

**Comment by NobbZ** [comment]
Touched emacs the first time again today after running the update. So far I do not see any changed behaviour!

Even without the `company-lsp` backend beeing installed and I still have the very same completion as I always have. So after this 15 minutes of work, I have to be honest, I do not see the necessity of using an alternative.

**Comment by adrien-barret** [comment]
can you put your configuration somewhere ?

**Comment by NobbZ** [comment]
It is already "somewhere" :D Not sure if it helps much, my configuration is generated from a nix-expression.

https://github.com/NobbZ/nix-dotfiles

**Comment by adrien-barret** [comment]
thanks

**Comment by tzohpilotl** [comment]
Any news on this? Can't install the package

**Comment by NobbZ** [comment]
Then remove it. It seems to not be necessary. After I removed it from the list of packages to install, emacs just behaved the same way than before.

**Comment by licht1stein** [comment]
Yes, removing it helps. It has also been patched out of prelude.
