### ISSUE TITLE
Wrong type argument: arrayp, nil" with args (prefix)

### ISSUE THREAD

**Issue by xianghx** [tigersoldier/company-lsp#17]
company-backends is a variable defined in ‘company.el’.
Its value is (company-lsp company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
             (company-dabbrev-code company-gtags company-etags company-keywords)
             company-oddmuse company-dabbrev)

Company: An error occurred in auto-begin
Company: backend company-lsp error "Wrong type argument: arrayp, nil" with args (prefix)
Quit
Saving file /home/xianghx/projects/variables/src/main.rs...
Error: (error "Rustfmt failed, see *rustfmt* buffer for details")

**Comment by xianghx** [comment]
(require-package 'lsp-mode)

(with-eval-after-load 'lsp-mode
  (require 'lsp-flycheck))


;; cargo install rustfmt
(require-package 'rust-mode)

(require-package 'flycheck-rust)

(add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-mode))

(with-eval-after-load 'rust-mode
  (setq rust-format-on-save t)

  (add-hook 'rust-mode-hook #'cargo-minor-mode)
  (add-hook 'rust-mode-hook #'lsp-mode)

  (add-hook 'rust-mode-hook #'flycheck-mode)
  (add-hook 'flycheck-mode-hook #'flycheck-rust-setup)
  )


(require-package 'lsp-rust)
(with-eval-after-load 'lsp-mode
  (setq lsp-rust-rls-command '("rustup" "run" "nightly" "rls"))
  ;; use the RLS_ROOT variable to locate the RLS,
  ;; (setq lsp-rust-rls-command nil)
  (require 'lsp-rust)
  (add-hook 'rust-mode-hook #'lsp-rust-enable)
  )


(require-package 'company-lsp)

(with-eval-after-load 'rust-mode
  (with-eval-after-load 'company

    (push 'company-lsp company-backends)
    ))
;; (with-eval-after-load 'rust-mode
;;   (with-eval-after-load 'company
;;     (add-hook 'rust-mode-hook (lambda () (set (make-local-variable 'company-backends)
;;                                          '(company-lsp
;;                                            (company-dabbrev-code company-gtags company-etags company-keywords)
;;                                            company-files company-dabbrev))))

;;     ))


(require-package 'cargo)
(with-eval-after-load 'cargo
  ;; (define-key cargo-minor-mode-map (kbd "<C-return>") 'cargo-process-repeat)
  (define-key cargo-minor-mode-map (kbd "<C-return>") 'cargo-process-run)
  (my-define-key
   :keymaps 'cargo-minor-mode-map

   "cn" 'cargo-process-new
   "ci" 'cargo-process-init

   "ce" 'cargo-process-bench
   "cb" 'cargo-process-build
   "cc" 'cargo-process-clean
   "crr" 'cargo-process-run               ; Build and execute src/main.rs.
   "cre" 'cargo-process-run-example       ; Build and execute with --example <name>.
   "crb" 'cargo-process-run-bin           ; Build and execute a specific binary.

   ;; "cl" 'cargo-process-repeat       ; Run the last cargo-process command.

   "cta" 'cargo-process-test                ; Run all unit tests.
   "ctt" 'cargo-process-current-test        ; Run the current unit test.
   "ctf" 'cargo-process-current-file-tests  ; Run the current file unit tests.

   "cd" 'cargo-process-doc       ; Build this project's and its dependencies' documentation.
   "ch" 'cargo-process-doc-open  ; Open this project's documentation.

   "cs" 'cargo-process-search    ; Search registry for crates.
   "cu" 'cargo-process-update    ; Update dependencies listed in Cargo.lock.

   "cf" 'cargo-process-fmt
   "ck" 'cargo-process-check
   "cy" 'cargo-process-clippy
   )
  )

**Comment by xianghx** [comment]
rustup component add rls-preview --toolchain nightly-2017-12-21
rustup component add rust-analysis --toolchain nightly-2017-12-21
rustup component add rust-src --toolchain nightly-2017-12-21

**Comment by xianghx** [comment]
ok.

**Comment by shackra** [comment]
I just experienced this issue
