### ISSUE TITLE
cquery completion problem

### ISSUE THREAD

**Issue by ram535** [tigersoldier/company-lsp#27]
I am using lsp-mode with cquery. Everything work fine except the completion. I am not sure if I configured something wrong.

This is the layout of the project where I am testing this configuration:

.
├── .cquery
└── [main.cpp](https://gist.github.com/ram535/d1ce054a2d0192459799aa37876f9acf)

.cquery

```
# Driver
clang++

# Language
-xc++
-std=c++11

# Includes
-I/work/cquery/third_party
```

This is my configuration:

```
     (use-package company
       :diminish ""
       :bind (:map company-active-map
                   ("C-j" . company-select-next)
                   ("<backtab>" . company-complete-common-or-cycle)
                   ("C-k" . company-select-previous))
       :custom
       (company-idle-delay 0.3)
       :config
       (global-company-mode))

     (use-package company-lsp
       :config
       (push 'company-lsp company-backends))

     (use-package lsp-mode
       :config
       (require 'lsp-flycheck))

     (use-package cquery
       :custom
       (cquery-executable "/home/last/bin/cquery/bin/cquery")
       (cquery-extra-args '("--log-file=/tmp/cq.log"))
       :config
       (add-hook 'c-mode-hook (lambda() (lsp-cquery-enable)))
       (add-hook 'c++-mode-hook (lambda() (lsp-cquery-enable))))
      ; only use company-lsp as a backend in c++-mode
       (add-hook 'c++-mode-hook (lambda ()
                                  (set (make-local-variable 'company-backends) '(company-lsp))
                                  (company-mode t)))

      (use-package flycheck
        :ensure t
        :config
        (add-hook 'c-mode-hook (lambda () (setq flycheck-checker 'lsp)))
        (add-hook 'c-mode-hook (lambda() (flycheck-mode)))
        (add-hook 'c++-mode-hook (lambda () (setq flycheck-checker 'lsp)))
        (add-hook 'c++-mode-hook (lambda() (flycheck-mode))))

```

I hope, I can be pointed if I have a error on my configuration or if there is an error somewhere.
Thanks.

**Comment by tigersoldier** [comment]
I can't spot anything wrong in your configuration. Can you provide the output of `M-x company-diag` and the content of the buffer `*lsp-cquery-stderr*`?

Another thing you can try is `M-x set-variable <RET> lsp-print-io <RET> t` to turn on LSP request logging, and see what's interesting in the `*Messages*` buffer.

**Comment by tigersoldier** [comment]
Can you paste the whole content of `company-diag`?

`-I/work/cquery/third_party` defines which directory you want to include for finding .h files. Not sure about `-xc++`. cc @maskray

**Comment by ram535** [comment]
```
Emacs 27.0.50 (x86_64-pc-linux-gnu) of 2018-02-15 on lgw01-amd64-002
Company 0.9.4

company-backends: (company-lsp)

Used backend: company-lsp
Major mode: c++-mode
Prefix: stop
Completions: none
```

**Comment by tigersoldier** [comment]
It seems your company-lsp version isn't compatible with lsp-mode. The version of companyflap is to old. Can you update companyflap and see if it works?

**Comment by ram535** [comment]
Now it works!!
I uninstall **company-lsp v1.0.0** from melpa-stable and then install **company-lsp v20180211.2052**
 from melpa.
Thanks for your help.

**Comment by tigersoldier** [comment]
That's good to know. Let me release a new version so that melpa-stable would pick up.

**Comment by MaskRay** [comment]
`-xc++` specified the language and it should come before the main source filename.

When the compiler driver is specified as a "C++-like" compiler (e.g. `g++` `c++` `clang++`), the `-xc++` has no use.
