### ISSUE TITLE
Documentation lookup?

### ISSUE THREAD

**Issue by Trevoke** [tigersoldier/company-lsp#28]
Hi,

Is it possible to retrieve documentation for the completion candidate, and if so, how?

**Comment by tigersoldier** [comment]
Company-lsp supports showing documentation if you have [company-quickhelp](https://github.com/expez/company-quickhelp) installed and enabled.

Your language server needs to support documentation.

**Comment by Trevoke** [comment]
Hey, sorry for the slow reply.

Here's the output of the capabilities server. The odd thing is, there's other documentation lookups that work just fine.

```
The server provides completion support
The server provides goto definition support
The server provides file formatting
The server provides file symbol support
The server provides hover support
The server provides references support
Document sync method: Send full contents
```

**Comment by tigersoldier** [comment]
It's different from the documentation for hover. The server has to populate `documentation` fields in the returned `CompletionItem` message. Details are available at the `CompletionItem` definition at https://microsoft.github.io/language-server-protocol/specification.

Currently you need to use [company-quickhelp](https://github.com/expez/company-quickhelp) for showing the documentation if the server provides.

To check if the server provides documentation, do the following:
 1. Enable `lsp-print-io`: `M-x set-variable RET lsp-print-io RET t`
 2. Trigger a completion.
 3. Go to the `*Messages*` buffer, find out the response of `textDocument/completion` and `completionItem/resolve`. See if `documentation` is in the responses.

**Comment by sebastiencs** [comment]
Alternatively to `company-quickhelp`, I made a company front-end which display documentation and icons with `company-lsp`: [company-box](https://github.com/sebastiencs/company-box)

**Comment by Trevoke** [comment]
This works supremely well. Thank you :)
