### ISSUE TITLE
prefix does not filter company candidates

### ISSUE THREAD

**Issue by ztlevi** [tigersoldier/company-lsp#30]
I'm trying to add `compnay-lsp` backend to `company-backends-js2-mode`. But once I add the `company-lsp` backend, company mode does not working properly to filter candidates when I typing.

This is how it looks like:

![791219c27c491f055320fee8f6c5bd034a7ffd75](https://user-images.githubusercontent.com/16655096/38182157-6c365f42-35ec-11e8-9189-ab99d2fc018e.gif)

Here is my setting:
```emacs lisp
(use-package lsp-javascript-typescript
    :commands (lsp-javascript-typescript-enable)
    :init
    (add-hook 'js-mode-hook #'lsp-javascript-typescript-enable)
    (add-hook 'typescript-mode-hook #'lsp-javascript-typescript-enable) ;; for typescript support
    (add-hook 'js2-mode-hook #'lsp-javascript-typescript-enable) ;; for js2-mode support
    (add-hook 'rjsx-mode #'lsp-javascript-typescript-enable) ;; for rjsx-mode support
    (spacemacs|add-company-backends
      :backends company-lsp
      :modes js2-mode)
    :defer t)
```

The value for `company-backends-js2-mode` is: 
```
Its value is ((company-lsp :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))
```

**Comment by ztlevi** [comment]
Looks like it's just `lsp-javascript` issue. I will open a new issue.

**Comment by tigersoldier** [comment]
As a workaround, you can set `company-lsp-cache-candidates` to `'auto` or `t` to let company-lsp or company-mode to do the filtering.

Note that some old versions of company-lsp have a bug the doesn't filter by prefix correctly. This should be fixed already.

**Comment by ztlevi** [comment]
`'auto` fix this for me in `lsp-javascript`. But it's so weird that it works for python and cquery without this...

**Comment by stardiviner** [comment]
I still have this issue, I tried set `company-lsp-cache-candidates` to different values. Still does not work.

**Comment by tigersoldier** [comment]
@stardiviner Can you try out PR #86?

**Comment by stardiviner** [comment]
I tried out your PR, confirmed it works. I didn't set any option like `company-lsp-cache-candidates` etc. Thanks for your work!!!
