### ISSUE TITLE
Incorrect Completion Inserted

### ISSUE THREAD

**Issue by nickenchev** [tigersoldier/company-lsp#33]
Hi, I've been using company-lsp + cquery for a month now and love how well everything works. I'm not sure if this is a cquery issue or related to this plugin, so I'll open issues for both.

When I start typing for a completion, emacs makes the suggestion, I hit enter too select it, but then the actual suggestion isn't inserted, but rather the last character (or 2) that I entered in order to get the suggestion. See the images below for an example using std::vector.

<img width="331" alt="screen shot 2018-04-09 at 11 55 56 am" src="https://user-images.githubusercontent.com/8262271/38508575-888d99f6-3bed-11e8-8eba-81ed81edd37d.png">

Now I start typing "std::ve" to get "vector" as a completion.

<img width="333" alt="screen shot 2018-04-09 at 11 56 08 am" src="https://user-images.githubusercontent.com/8262271/38508596-9d7fa408-3bed-11e8-9682-7e7865db21d7.png">

I hit enter and get the following result:
<img width="337" alt="screen shot 2018-04-09 at 11 56 17 am" src="https://user-images.githubusercontent.com/8262271/38508607-a3df06e0-3bed-11e8-9e2a-2c140c98c0b0.png">

**Comment by tigersoldier** [comment]
There is a bug in how company-lsp handles textEdit with snippet support. 033b345534b7016213357f467de95de2440e59e0 is supposed to fix this. In case I introduced new bug because sleepy coding, I'll review it myself tomorrow then merge it.

**Comment by nickenchev** [comment]
Hey, this is definitely something fairly new, I'm just not sure if it is somehow caused by the latest cquery executable. I've been using company-lsp with cquery for a little while now and haven't see this until my recent update. I found this new one instantly after updating. Have you tried to replicate it? It behaves this way pretty consistently.

**Comment by nickenchev** [comment]
FYI, I've opened issues with cquery and emacs-lsp. Cquery author reverted a commit which broke the completions in emacs, and it resolved the issue. This is apparently caused by unsupported features in the completions API by emacs-lsp.

https://github.com/cquery-project/cquery/issues/606
https://github.com/emacs-lsp/lsp-mode/issues/339

**Comment by tigersoldier** [comment]
This should be fixed by #36
