### ISSUE TITLE
Company lsp must use client renderers to render the help

### ISSUE THREAD

**Issue by yyoncho** [tigersoldier/company-lsp#42]
Similar to what `lsp-ui` is doing.

**Comment by tigersoldier** [comment]
Sorry for the long delay. How does lsp-ui use client render to render help?

**Comment by yyoncho** [comment]
I believe that `company-lsp` should use `lsp--render-on-hover-content` if possible to reuse(or change the method so it is reusable). `lsp-ui` is reimplementing this logic, but I believe that the logic must live in `lsp-mode`.
