### ISSUE TITLE
Company: backend company-lsp error "Wrong type argument: lsp--workspace, nil" with args (prefix)

### ISSUE THREAD

**Issue by xianghx** [tigersoldier/company-lsp#51]
Company: backend company-lsp error "Wrong type argument: lsp--workspace, nil" with args (prefix)
Error during redisplay: (eval (lsp-mode-line)) signaled (wrong-type-argument lsp--workspace nil) [6 times]

rust lastest

**Comment by xianghx** [comment]
delete package, reinstall.

**Comment by vyorkin** [comment]
facing the same error and reinstall doesn't work for me:

```
Debugger entered--Lisp error: (wrong-type-argument lsp--workspace nil)
  signal(wrong-type-argument (lsp--workspace nil))
  company-lsp(prefix)
  apply(company-lsp prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) company-lsp)
  company-call-backend(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  company-complete()
  funcall-interactively(company-complete)
  call-interactively(company-complete nil nil)
  command-execute(company-complete)
```

here is my config `company-lsp` config:

```
(use-package company-lsp
  :requires (init-quelpa init-company)
  :after (lsp-mode company)
  :quelpa (company-lsp :fetcher github :repo "tigersoldier/company-lsp")
  :init
  (setq
   company-transformers nil
   company-lsp-cache-candidates t
   company-lsp-async t
   company-lsp-enable-snippet t)
  :config
  (push 'company-lsp company-backends))
```

**Comment by yyoncho** [comment]
This probably means that lsp server has crashed. Check the \*err\* buffer.

**Comment by vyorkin** [comment]
I can't find the `*err*` buffer, but in `*Messages*` I have this:

```
Company: An error occurred in auto-begin
Company: backend company-lsp error "Wrong type argument: lsp--workspace, nil" with args (prefix)
```

![image](https://user-images.githubusercontent.com/988849/48198110-d71e6f00-e368-11e8-969a-156bb3c79375.png)

**Comment by yyoncho** [comment]
From what I can see lsp-haskell uses this command to generate the server command:

` (funcall lsp-haskell-process-wrapper-function (lsp--haskell-hie-command))`

Can you execute the code above and then try to run that from the command line. This might unveil what is the causing the server crash.

**Comment by xianghx** [comment]
I use rust:
```
(with-eval-after-load 'rust-mode
  (setq rust-format-on-save t)

  (setq rust-rustfmt-bin "~/.rustup/toolchains/nightly-i686-unknown-linux-gnu/bin/rustfmt")
  (setq lsp-rust-rls-command '("rustup" "run" "nightly" "rls"))

  (require 'lsp-mode)
  (add-hook 'rust-mode-hook #'lsp-mode)
   (with-eval-after-load 'lsp-mode
     (require 'lsp-rust)
     (add-hook 'rust-mode-hook #'lsp-rust-enable))

  (add-hook 'rust-mode-hook 'company-mode)
  (add-hook 'rust-mode-hook (lambda () (set (make-local-variable 'company-backends)
                                       '(company-lsp
                                         (company-dabbrev-code company-gtags company-etags company-keywords)
                                         company-files company-dabbrev))))

  )

```

**Comment by vyorkin** [comment]
@yyoncho output of 

```
(funcall lsp-haskell-process-wrapper-function (lsp--haskell-hie-command))
```

is

```
("hie-wrapper" "--lsp" "-d" "-l" "/tmp/hie.log")
```

I've just tried executing `hie-wrapper --lsp -d -l /tmp/hie.log` from the command line and it seem to work just fine

![image](https://user-images.githubusercontent.com/988849/48204286-7dbf3b80-e37a-11e8-8e16-54462d00c767.png)

**Comment by vyorkin** [comment]
yeah, sure, here is what I have so far https://gist.github.com/vyorkin/58c1b30a7b33db2e9fd34591ec6f7278

**Comment by xianghx** [comment]
@yyoncho  thanks.  we don't need it. I reopen the problem.
```
(with-eval-after-load 'rust-mode
  (require 'lsp-mode)
   (with-eval-after-load 'lsp-mode
     (require 'lsp-rust)
     (add-hook 'rust-mode-hook #'lsp-rust-enable))
  )
```

**Comment by vyorkin** [comment]
ok, I've found what caused the issue: I was enabling `(lsp-mode)` before `(lsp-haskell-enable)`. I've just commented out `(lsp-mode)` and now it is working. here is how I've found it: https://github.com/emacs-lsp/lsp-java/issues/38#issuecomment-400770831

**Comment by xianghx** [comment]
Sure. The problem is solved, so I close it.
