### ISSUE TITLE
Yasnippet candidates with semantic completion like dot or arrow

### ISSUE THREAD

**Issue by andreyorst** [tigersoldier/company-lsp#60]
Hello. I have an issue with cquery + emacs-cquery + company + company-lsp + yasnippet. May'be I'm missing something, but I can't just find how to configure this bundle properly. Heres' what I've did:

```elisp
(use-package company :ensure t
  :init
  (setq company-require-match 'never
        company-transformers 'nil
        company-minimum-prefix-length 2
        company-lsp-async t
        company-lsp-cache-candidates nil
        company-frontends
        '(company-pseudo-tooltip-unless-just-one-frontend
          company-preview-frontend
          company-echo-metadata-frontend))
  :config
  (setq company-backends (remove 'company-clang company-backends)
        company-backends (remove 'company-xcode company-backends)
        company-backends (remove 'company-gtags company-backends)
        company-backends (remove 'company-cmake company-backends))
  (add-hook 'after-init-hook 'global-company-mode)
  (define-key company-active-map (kbd "TAB") 'company-complete-common-or-cycle)
  (define-key company-active-map (kbd "<tab>") 'company-complete-common-or-cycle)
  (define-key company-active-map (kbd "S-TAB") 'company-select-previous)
  (define-key company-active-map (kbd "<backtab>") 'company-select-previous))

(use-package yasnippet :ensure t
  :config
  (add-hook 'prog-mode-hook 'yas-minor-mode))

(use-package yasnippet-snippets :ensure t)

(use-package company-lsp :ensure t
  :config
  (push '(company-lsp :with company-yasnippet) company-backends))

(use-package lsp-mode :ensure t)
```
I'm still a newbie so configuration is pretty much based on projects wikis. 

The problem is, if I add a 'company-yasnippet` to `company-backends` before `company-lsp` I'll get only snippets, and no completions from cquery. However, if I do as it said in <kbd>Ctrl h</kbd><kbd>o</kbd><kbd>Ret</kbd> `company-yasnippet` - use `(push ... ...)` to add `company lsp :with company-yasnippet` to `company-backends` I can have both snippet and lsp completions altogether. However, there's no sorting needed according to `cquery` Wiki, and therefore snippet candidates are shown somewhat not in the right place:

![image](https://user-images.githubusercontent.com/19470159/46583023-ec963580-ca58-11e8-8caf-4c2d4a7fa977.png)

and the candidates are way down in the list:

![image](https://user-images.githubusercontent.com/19470159/46583031-06d01380-ca59-11e8-81dc-e525954c8308.png)

I don't understand why do I end up with whole snippet definitions in the popup, because when I type `for`:

![image](https://user-images.githubusercontent.com/19470159/46583051-5282bd00-ca59-11e8-8a21-4acc18f20a78.png)

I see reasonable (well except those UPPERCASE items... I really want it to respect case, and stay fuzzy, but I don't know how) completion. So why does writing dot `.`, or arrow `->` shows snippets, and how I can avoid that? I don't feel like this results are really needed there at all, because those two triggers are semantic ones. But even moving snippets to the end of the list will fix the problem, but unfortunately there's no priorities AFAIK for sources in company.

**Comment by andreyorst** [comment]
nvm.

**Comment by tigersoldier** [comment]
In general it's not recommended to add `company-yasnippet` into your `company-backends`. company-lsp disables company-mode sorting in favor of custom sorting provided by language servers. This unfortunately doesn't work well with company's multi-backend feature. Maybe providing custom variables to enable sorting by company mode can solve this issue.

As of the candidate for `for`, I don't know the details in cquery. My guess is cquery does fuzzy matching so __**F**LT16_DEN**OR**M_MIN__ matches `for`
