### ISSUE TITLE
Wrong completion with http.HandleFunc

### ISSUE THREAD

**Issue by manateelazycat** [tigersoldier/company-lsp#71]
Hi tiger

![company-lsp-bug](https://user-images.githubusercontent.com/237487/49071154-54524b00-f268-11e8-8bff-2948ab670c31.gif)

When i type http.HandleFunc , i got bug like above gif.

I debug in code, i found insert-text will become 
```
http.HandleFunc(${1:pattern string}, ${2:handler func(http.ResponseWriter}, ${3:*http.Request})$0
```

I think right snippet should be:
```
http.HandleFunc(${1:pattern string}, ${2:handler func(http.ResponseWriter, ${3:*http.Request})})$0
```

Don't know is a bug of company-lsp? 

If it is, hope above can help you fix it.

Thanks for build company-lsp. ;)

**Comment by tigersoldier** [comment]
The snippet is returned from go-langserver directly. I highly suspect it's a bug on their side.

Unfortunately I couldn't enable snippet in VS code so couldn't verify it.

**Comment by manateelazycat** [comment]
I use my own Nox, so close issue.
