### ISSUE TITLE
Placeholders in the selected completion

### ISSUE THREAD

**Issue by BiagioFesta** [tigersoldier/company-lsp#75]
# Issue
The completion works fine, the suggested candidate is correct:

![companylspbefore](https://user-images.githubusercontent.com/15035284/49932032-6834b880-fec8-11e8-9285-61f080bfea89.PNG)

However, if I select the candidate (press `Enter`) the completion does not handle the backend placeholders (`$1`, `$0`, ...) for the arguments.

That's the result:
![companylspafter](https://user-images.githubusercontent.com/15035284/49932125-90bcb280-fec8-11e8-9ef8-cbfd5268fa6d.PNG)

# Environment
* `GNU Emacs` 25.2.2
* `lsp-mode` 20181211.1641 (Melpa)
* `company-lsp` 20181202.1700 (Melpa)
* `lsp-ui` 20181209.123 (Melpa)
* LSP Clients tested (same problem with both):
    * `cquery` 20181203.1829 (Melpa) (C++)
    * `ccls` 20181209.1811 (Melpa) (C++)

**Comment by yyoncho** [comment]
Do you have yassnippet installed/enabled?

**Comment by BiagioFesta** [comment]
> Do you have yassnippet installed/enabled?

I don't have. 
Do you mean [this yasnippet](https://github.com/joaotavora/yasnippet)?

**Comment by BiagioFesta** [comment]
Sorry I've just noticed

> Expand snippets on completion (requires yasnippet).

in the [README.md](https://github.com/tigersoldier/company-lsp/blob/master/README.md)

My bad!

---

After `yasnippet` installation, it properly works.

I am going to close the issue.
Thank you for the support!

**Comment by madscientist** [comment]
Is it possible to recognize that yasnippet is not enabled, and fall back to simply completing the function name without filling in the weird content that doesn't work without yasnippet?  I guess emacs-lsp/lsp-mode#542 may make this obsolete if it depends on yasnippet.

**Comment by yyoncho** [comment]
@madscientist yes we should, but it all depends on  emacs-lsp/lsp-mode#542 decision.

**Comment by liar666** [comment]
Hi,

I've got the following packages installed:
`yasnippet          20200604.246  dependency            Yet another snippet extension for Emacs` from MELPA
and
`company            20210721.2003 dependency            Modular text completion framework` from MELPA
and
`company-lsp        20190612.1553 installed             Company completion backend for lsp-mode.` from ???
but I still have the problem with the completion not handling the backend placeholders... Is that normal?
