### ISSUE TITLE
YaSnippet completion is putting the completed text in the wrong location

### ISSUE THREAD

**Issue by DougBeney** [tigersoldier/company-lsp#78]
[Here's the problem](https://imgur.com/VIdA7J3). I am trying to use a completion and it puts the completed text in the wrong location. 

From what it looks like, YaSnippet checks the parameter list and finds the first instance of the text before the completion. In this example it is "error." - and once it finds that first occurrence, it appends there rather than where it is supposed to. 

company-lsp version: 20181226.709

lsp-mode version: 20190101.1354

YaSnippet version: 20181015.1212

EDIT: Here's [another](https://imgur.com/AqXNNsr) recording of a similar situation.

**Comment by janoc** [comment]
I have seen this happening too! Also using the same config - company-lsp, lsp and yasnippet, with cquery as the lsp backend.

**Comment by yyoncho** [comment]
Can you provide logs from client/server communication and also the output of `company-diag` just before pressing enter?

**Comment by janoc** [comment]
I need to find a reproducible test case first - it doesn't always happen for me.

**Comment by s-kostyaev** [comment]
For me it happens sometimes after a lot of text edits and undos and maybe some `C-g` with bingo backend.

**Comment by tigersoldier** [comment]
What's the value of `company-lsp-cache-candidates`? 

In general if a language server returns text edit (which I think is true for ccls, not sure about bingo), company-lsp just applies what the server returns. Looks like something is out of sync.

**Comment by Jimx-** [comment]
If I cleanup the completion cache manually(by `(setq company-lsp--completion-candidate nil)`) after this happens then company-lsp will start to apply completions to correct locations again. Maybe some outdated cache entries are not removed from the cache after the completion finishes.

**Comment by tigersoldier** [comment]
After reading the code I noticed that the clear cache function was added to and removed from company hooks globally. It should be added local to the buffer. #80 should fix it.
