### ISSUE TITLE
please release new version

### ISSUE THREAD

**Issue by thkoch2001** [tigersoldier/company-lsp#81]
There is time until end of February to package company-lsp for Debian. I'm about to upload lsp-mode and lsp-mode version 6.0 in the next days.

Do you think it is worth releasing a new version of company-lsp in the next days or is 2.0.2 a good candidate to be installed alongside lsp 6.0?

**Comment by yyoncho** [comment]
2.0.2 won't work with lsp-mode 6.0

**Comment by tigersoldier** [comment]
Released 2.1.0
