### ISSUE TITLE
Disabling yasnippets doesn't work

### ISSUE THREAD

**Issue by dakra** [tigersoldier/company-lsp#85]
When I set `company-lsp-enable-snippet` to `NIL`
I still get the yasnippet expandsion but no activated
yasnippet mode.
E.g. I would literally get `initialize_module(${1:emacs_env *env})$0`
after completing `initi<tab>`.

**Comment by yyoncho** [comment]
Use lsp-enable-snippet

**Comment by dakra** [comment]
Disabling `lsp-enable-snippet` also doesn't work for me. It doesn't expand the snippets but still completes with the meta syntax like I showed above.

But I only tried it with `ccls` and my compnay setup might be different from normal as well (I use the `tng-frontend).

I have simply snippets enabled now and I won't have time to debug this issue better and give an example with a more minimal setup. Feel free to close this issue and I'll reopen when I have a bit more time.

**Comment by rrudakov** [comment]
![output-2019-03-06-14 09 09](https://user-images.githubusercontent.com/6093590/53880513-d72e3300-4019-11e9-90d2-5d7324ba73c3.gif)
I have similar issue for pyls, snippets are disabled, but sometimes company expand placeholders.

**Comment by subsonik** [comment]
I have the same problem. Also using pyls. It'd be cool if there was an option to disable auto-insertion of arguments altogether, e.g. 'fun' completes to 'func()', instead of 'func(arg1, arg2, arg3)'.

**Comment by puhsu** [comment]
I have same problem with pyls. I think this issue https://github.com/palantir/python-language-server/issues/515 might be related. I downgraded pyls version for now (`pip3 install -U --user python-language-server==0.22.0`)

**Comment by subsonik** [comment]
> I have same problem with pyls. I think this issue [palantir/python-language-server#515](https://github.com/palantir/python-language-server/issues/515) might be related. I downgraded pyls version for now (`pip3 install -U --user python-language-server==0.22.0`)

Was just about to post this myself. Thanks for the tip re: downgrading!

**Comment by dakra** [comment]
I close this issue now. The `pyls` issue is not directly related and my initial problem was caused that `company-tng` disables `post-completions`, see https://github.com/company-mode/company-mode/commit/248222320ec56f0df966e22acece08239f702564

So I just switched to another company frontend.
