### ISSUE TITLE
Completion can not work any more when update company-lsp

### ISSUE THREAD

**Issue by maobaoqi** [tigersoldier/company-lsp#92]
Hi, When I update company-lsp new commit "218898c", LSP based on clang can not work on my laptop.I write some demo C and C++ code and it is likely that company-lsp can not be called by LSP, it works using company-clang.And I go back to previous company-lsp commit, emacs can show correctly completion using company-lsp.

I don't know where is going wrong.

**Comment by tigersoldier** [comment]
Hi, what's the language server you are using? Is it ccls, cquery, or clangd?

Can you try `M-x company-lsp` and paste the output here?

**Comment by maobaoqi** [comment]
@tigersoldier I use clangd as c and c++ server. I try `M-x company-lsp`, it shows `Cannot complete at point` in minibuffer.

**Comment by maobaoqi** [comment]
@tigersoldier Type `M-x company-lsp` on a blank line of c code, emacs can show completion menu using 
 company-lsp, but the menu contains few completion items, no complete c standard library funtions. Old company-lsp can work well.

**Comment by tigersoldier** [comment]
@maobaoqi I just commited #93 and #94 which should fix the clangd filtering issue. Please update to the latest version. MELPA should pick up the changes in an hour or two.

**Comment by maobaoqi** [comment]
@tigersoldier I test it right now and it works! thank you for so quick fix.
