### ISSUE TITLE
company is not used

### ISSUE THREAD

**Issue by ArataSakamaki** [tigersoldier/company-lsp#96]
Hello.
I want to use company-lsp for python completion and maybe completion are working. but different from what I expected. Complation list are showed in another buffer like follwoing gif

How do I get to work like company-lsp README gif

My version is 
emacs                26.1
company           20190316.101
company-lsp    20190314.710
lsp-mode          20190317.142

and this is my init.el

~~~
(require 'company)
(global-company-mode)

(require 'lsp-mode)
(add-hook 'prog-mode-hook #'lsp)

(require 'lsp-ui)
(add-hook 'lsp-mode-hook 'lsp-ui-mode)

(require 'company-lsp)
(push 'company-lsp company-backends)
~~~

![emacs-lsp](https://user-images.githubusercontent.com/28821947/54619275-b0570e80-4aa7-11e9-859e-5f134e453929.gif)

**Comment by tigersoldier** [comment]
I don't see LSP in your mode line. It's possible that you didn't install python language server correctly, or the python language server is not discovered by lsp-mode. Can you share the content of `*lsp-logs* buffer and the installation directory of python language server?

**Comment by tigersoldier** [comment]
From the logs it seems that LSP server is working. Did you install `jedi`? If yes, try disabling it.

Also, what happens if you do `M-x company-lsp <RET>` in a place that can complete?

**Comment by ArataSakamaki** [comment]
I didin't install jedi and ```M-x company-lsp``` returns "cannot complete at point"

**Comment by tigersoldier** [comment]
Found another possibility: `python-mode` (see company-mode/company-mode#37)

If you are not using `python-mode` either, or disabling doesn't make company-lsp work, can you share your .emacs file in gist, and the output of `M-x lsp-describe-session` and `M-x company-diag`?

**Comment by ArataSakamaki** [comment]
my init.el
https://gist.github.com/ArataSakamaki/71156db54264391789310db62dbc95df

`M-x lsp-describe-session` returns nothing in buffer.

`M-x company-diag`
~~~
Emacs 26.1 (x86_64-apple-darwin14.5.0) of 2018-05-31 on builder10-10.porkrind.org
Company 0.9.9

company-backends: (company-lsp company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	     (company-dabbrev-code company-gtags company-etags company-keywords)
	     company-oddmuse company-dabbrev)

Used backend: (company-dabbrev-code company-gtags company-etags company-keywords)

Major mode: python-mode
Prefix: #("arra" 0 4
  (fontified t))

Completions: none
~~~

**Comment by tigersoldier** [comment]
So `python-mode` is used. Try `(require python)` instead. This will stop the completion behavior you currently see.

However this won't get you completion from `company-lsp`, as lsp-mode is not activated here. @yyoncho can you provide guidance in diagnosing why pyls is not working?

**Comment by yyoncho** [comment]
@ArataSakamaki I tested your config and it works fine. I suspect that you do hot have pyls properly configured(e. g. it is not on classpath). Inpsect `*lsp-log*` for more details.

**Comment by ArataSakamaki** [comment]
@yyoncho  thanks for the reply
I think when I choose project setting config, I may have added the project to lsp-session-folder-blacklist, so lsp is not working.
How can I delete blacklist?

**Comment by yyoncho** [comment]
```(setq lsp--session (make-lsp-session))``` or delete `lsp-session-file`

**Comment by ArataSakamaki** [comment]
@tigersoldier @yyoncho 
thanks! working correctly
